const mongoose = require("mongoose");

/**
 * CareerRecommendation schema
 * Stores the latest set of career suggestions generated by the
 * Career Recommendation Agent for a student, each with a reason.
 */
const careerRecommendationSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    careers: [
      {
        title: String,
        reason: String,
      },
    ],
  },
  { timestamps: true }
);

module.exports = mongoose.model("CareerRecommendation", careerRecommendationSchema);
