const mongoose = require("mongoose");

/**
 * StudentProfile schema
 * Holds the education/interests/goals data collected from the student,
 * plus the summarized output produced by the Profile Analysis Agent
 * and the skill gap output produced by the Skill Assessment Agent.
 */
const studentProfileSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, unique: true },

    // Raw input collected from the student
    education: {
      degree: String,
      branch: String,
      year: String,
      cgpa: String,
    },
    interests: [String],
    goals: String,
    currentSkills: [String],
    targetRole: String,

    // Output generated by the Profile Analysis Agent (LangGraph)
    profileSummary: { type: String, default: "" },

    // Output generated by the Skill Assessment Agent (LangGraph)
    skillGapAnalysis: {
      requiredSkills: [String],
      missingSkills: [String],
      matchedSkills: [String],
      readinessScore: Number,
    },

    // LangGraph thread id used so the agent service can recall memory for this student
    agentThreadId: { type: String },
  },
  { timestamps: true }
);

module.exports = mongoose.model("StudentProfile", studentProfileSchema);
