import { useEffect, useState } from "react";
import DashboardLayout from "../components/DashboardLayout";
import axiosClient from "../api/axiosClient";

/**
 * CareerRecommendation page.
 * Displays the latest saved recommendations (GET /api/career) and lets
 * the student re-run the Career Recommendation Agent on demand
 * (POST /api/career/recommend).
 */
export default function CareerRecommendation() {
  const [recommendation, setRecommendation] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");

  const load = () => {
    axiosClient
      .get("/career")
      .then(({ data }) => setRecommendation(data))
      .catch(() => setRecommendation(null))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    load();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    setError("");
    try {
      const { data } = await axiosClient.post("/career/recommend");
      setRecommendation(data);
    } catch (err) {
      setError(err.response?.data?.message || "Could not generate recommendations.");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <DashboardLayout title="Career Recommendation">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <p className="max-w-xl text-sm text-ink-500">
          Generated by the Career Recommendation Agent using your profile summary and skill gap analysis.
        </p>
        <button onClick={handleGenerate} disabled={generating} className="btn-primary shrink-0">
          {generating ? "Thinking..." : "Regenerate recommendations"}
        </button>
      </div>

      {error && <p className="mb-4 text-sm text-rose-300">{error}</p>}

      {loading ? (
        <p className="text-ink-500">Loading...</p>
      ) : recommendation?.careers?.length ? (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {recommendation.careers.map((c, i) => (
            <div key={i} className="glass-panel p-5">
              <div className="mb-3 h-1.5 w-10 rounded-full bg-gradient-to-r from-accent-indigo to-accent-violet" />
              <h3 className="mb-2 text-lg font-semibold text-white">{c.title}</h3>
              <p className="text-sm leading-relaxed text-ink-300">{c.reason}</p>
            </div>
          ))}
        </div>
      ) : (
        <div className="glass-panel p-8 text-center">
          <p className="text-ink-300">No recommendations yet.</p>
          <p className="mt-1 text-sm text-ink-500">
            Complete your profile and run AI analysis first, then generate recommendations here.
          </p>
        </div>
      )}
    </DashboardLayout>
  );
}
