import { useEffect, useState } from "react";
import DashboardLayout from "../components/DashboardLayout";
import axiosClient from "../api/axiosClient";

/**
 * LearningRoadmap page.
 * Displays the saved roadmap (GET /api/roadmap) - ordered steps,
 * certifications, projects, and courses - and lets the student regenerate
 * it (POST /api/roadmap/generate), which runs the Learning Roadmap Agent
 * chained with the Course Recommendation Agent.
 */
export default function LearningRoadmap() {
  const [roadmap, setRoadmap] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");

  const load = () => {
    axiosClient
      .get("/roadmap")
      .then(({ data }) => setRoadmap(data))
      .catch(() => setRoadmap(null))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    load();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    setError("");
    try {
      const { data } = await axiosClient.post("/roadmap/generate");
      setRoadmap(data);
    } catch (err) {
      setError(err.response?.data?.message || "Could not generate roadmap.");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <DashboardLayout title="Learning Roadmap">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <p className="max-w-xl text-sm text-ink-500">
          Step-by-step plan, certifications, projects, and courses generated by the Learning Roadmap and Course
          Recommendation Agents based on your missing skills.
        </p>
        <button onClick={handleGenerate} disabled={generating} className="btn-primary shrink-0">
          {generating ? "Building roadmap..." : "Regenerate roadmap"}
        </button>
      </div>

      {error && <p className="mb-4 text-sm text-rose-300">{error}</p>}

      {loading ? (
        <p className="text-ink-500">Loading...</p>
      ) : roadmap?.steps?.length ? (
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <div className="glass-panel p-6 lg:col-span-2">
            <h2 className="mb-4 text-lg font-semibold text-white">Step-by-step path</h2>
            <ol className="space-y-4">
              {roadmap.steps.map((s, i) => (
                <li key={i} className="flex gap-4">
                  <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-accent-indigo to-accent-violet text-sm font-bold text-white">
                    {i + 1}
                  </div>
                  <div>
                    <p className="font-medium text-ink-100">{s.step}</p>
                    <p className="mt-0.5 text-sm text-ink-500">{s.description}</p>
                  </div>
                </li>
              ))}
            </ol>
          </div>

          <div className="space-y-6">
            <div className="glass-panel p-6">
              <h3 className="mb-3 text-sm font-semibold text-ink-100">Recommended certifications</h3>
              <ul className="space-y-2">
                {roadmap.certifications?.map((c, i) => (
                  <li key={i} className="text-sm text-ink-300">🎓 {c}</li>
                ))}
              </ul>
            </div>
            <div className="glass-panel p-6">
              <h3 className="mb-3 text-sm font-semibold text-ink-100">Suggested projects</h3>
              <ul className="space-y-2">
                {roadmap.projects?.map((p, i) => (
                  <li key={i} className="text-sm text-ink-300">🛠 {p}</li>
                ))}
              </ul>
            </div>
            <div className="glass-panel p-6">
              <h3 className="mb-3 text-sm font-semibold text-ink-100">Recommended courses</h3>
              <ul className="space-y-3">
                {roadmap.courses?.map((c, i) => (
                  <li key={i} className="text-sm">
                    <p className="font-medium text-ink-100">{c.title}</p>
                    <p className="text-xs text-ink-500">{c.platform} • covers {c.skill}</p>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      ) : (
        <div className="glass-panel p-8 text-center">
          <p className="text-ink-300">No roadmap yet.</p>
          <p className="mt-1 text-sm text-ink-500">
            Complete your profile and run AI analysis first, then generate a roadmap here.
          </p>
        </div>
      )}
    </DashboardLayout>
  );
}
